services:
  newsletter-db:
    image: postgres:17-alpine
    env_file: .env
    expose:
      - 5432
    networks:
      - newsletter-net
    ports:
      - 5432:5432
    volumes:
      - newsletter-db:/var/lib/postgresql/data
  newsletter-valkey:
    command: valkey-server --save 60 1 --loglevel debug
    image: valkey/valkey:8.0-alpine
    env_file: .env
    expose:
      - 6379
    networks:
      - newsletter-net
    ports:
      - 6379:6379
    volumes:
      - newsletter-valkey:/data
  newsletter-test-db:
    image: postgres:17-alpine
    env_file: .env.test
    expose:
      - 54321
    networks:
      - newsletter-test-net
    ports:
      - 54321:54321
  newsletter-test-valkey:
    command: valkey-server --port 63791 --save 60 1 --loglevel debug
    image: valkey/valkey:8.0-alpine
    env_file: .env.test
    expose:
      - 63791
    networks:
      - newsletter-test-net
    ports:
      - 63791:63791
volumes:
  newsletter-db:
  newsletter-valkey:
networks:
  newsletter-net:
    driver: bridge
    name: newsletter-net
  newsletter-test-net:
    driver: bridge
    name: newsletter-test-net
